version: '3.7'

services:
  my-mysql:
    image: mysql:8.0.18
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=asdf5678
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../../Storage/my-mysql/data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
      